import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";
import type { Tournament, Match, Standing, Team, Referee } from "@/types";

interface PDFColors {
  primary: [number, number, number];
  dark: [number, number, number];
  light: [number, number, number];
  white: [number, number, number];
  gray: [number, number, number];
}

const COLORS: PDFColors = {
  primary: [37, 99, 235],
  dark: [15, 23, 42],
  light: [241, 245, 249],
  white: [255, 255, 255],
  gray: [100, 116, 139],
};

function addHeader(doc: jsPDF, tournament: Tournament, title: string) {
  const pageWidth = doc.internal.pageSize.getWidth();

  // Background header
  doc.setFillColor(...COLORS.dark);
  doc.rect(0, 0, pageWidth, 28, "F");

  // Tournament name
  doc.setFontSize(14);
  doc.setTextColor(...COLORS.white);
  doc.setFont("helvetica", "bold");
  doc.text(tournament.name, 14, 12);

  // Report title
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);
  doc.setFont("helvetica", "normal");
  doc.text(title, 14, 20);

  // Date top right
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(format(new Date(), "dd.MM.yyyy HH:mm"), pageWidth - 14, 12, { align: "right" });
  doc.text(tournament.location, pageWidth - 14, 20, { align: "right" });
}

function addFooter(doc: jsPDF, pageNum: number, total: number) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  doc.setFillColor(...COLORS.light);
  doc.rect(0, pageHeight - 12, pageWidth, 12, "F");

  doc.setFontSize(7);
  doc.setTextColor(...COLORS.gray);
  doc.setFont("helvetica", "normal");
  doc.text("Generated by Tournify", 14, pageHeight - 4);
  doc.text(`Page ${pageNum} of ${total}`, pageWidth - 14, pageHeight - 4, { align: "right" });
}

export function exportFullSchedule(
  tournament: Tournament,
  matches: Match[],
  locale = "en"
): void {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();

  addHeader(doc, tournament, "Full Schedule");

  const tableData = matches
    .sort((a, b) => new Date(a.scheduled_at).getTime() - new Date(b.scheduled_at).getTime())
    .map((m) => [
      m.match_number.toString(),
      format(new Date(m.scheduled_at), "HH:mm"),
      m.pitch?.name ?? "–",
      m.group?.name ?? "–",
      m.home_team?.name ?? "TBD",
      m.away_team?.name ?? "TBD",
      m.status === "completed"
        ? `${m.home_score ?? 0}–${m.away_score ?? 0}`
        : "–",
      m.referee?.name ?? "–",
    ]);

  autoTable(doc, {
    startY: 34,
    head: [["#", "Time", "Pitch", "Group", "Home", "Away", "Score", "Referee"]],
    body: tableData,
    headStyles: {
      fillColor: COLORS.primary,
      textColor: COLORS.white,
      fontStyle: "bold",
      fontSize: 8,
    },
    bodyStyles: {
      fontSize: 8,
      textColor: COLORS.dark,
    },
    alternateRowStyles: {
      fillColor: COLORS.light,
    },
    columnStyles: {
      0: { cellWidth: 8 },
      1: { cellWidth: 14 },
      2: { cellWidth: 18 },
      3: { cellWidth: 16 },
      4: { cellWidth: 35 },
      5: { cellWidth: 35 },
      6: { cellWidth: 16 },
      7: { cellWidth: 35 },
    },
    margin: { left: 14, right: 14 },
  });

  addFooter(doc, 1, 1);
  doc.save(`${tournament.name.replace(/\s+/g, "-")}-schedule.pdf`);
}

export function exportStandings(
  tournament: Tournament,
  standingsByGroup: Record<string, Standing[]>,
  locale = "en"
): void {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  addHeader(doc, tournament, "Standings Report");

  let currentY = 34;
  const groups = Object.entries(standingsByGroup);

  groups.forEach(([groupName, standings], idx) => {
    if (idx > 0) currentY += 6;

    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...COLORS.dark);
    doc.text(`Group ${groupName}`, 14, currentY);
    currentY += 4;

    autoTable(doc, {
      startY: currentY,
      head: [["#", "Team", "P", "W", "D", "L", "GF", "GA", "GD", "Pts"]],
      body: standings.map((s, i) => [
        (i + 1).toString(),
        s.team.name + (s.advances ? " ↑" : ""),
        s.played.toString(),
        s.won.toString(),
        s.drawn.toString(),
        s.lost.toString(),
        s.goals_for.toString(),
        s.goals_against.toString(),
        (s.goal_difference > 0 ? "+" : "") + s.goal_difference,
        s.points.toString(),
      ]),
      headStyles: {
        fillColor: COLORS.primary,
        textColor: COLORS.white,
        fontStyle: "bold",
        fontSize: 8,
      },
      bodyStyles: {
        fontSize: 8,
        textColor: COLORS.dark,
      },
      alternateRowStyles: { fillColor: COLORS.light },
      columnStyles: {
        0: { cellWidth: 8 },
        1: { cellWidth: 50 },
        2: { cellWidth: 10 },
        3: { cellWidth: 10 },
        4: { cellWidth: 10 },
        5: { cellWidth: 10 },
        6: { cellWidth: 10 },
        7: { cellWidth: 10 },
        8: { cellWidth: 10 },
        9: { cellWidth: 12 },
      },
      margin: { left: 14, right: 14 },
    });

    currentY = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 4;
  });

  addFooter(doc, 1, 1);
  doc.save(`${tournament.name.replace(/\s+/g, "-")}-standings.pdf`);
}

export function exportRefereeSheet(
  tournament: Tournament,
  referee: Referee,
  matches: Match[],
  locale = "en"
): void {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();

  addHeader(doc, tournament, `Referee Sheet — ${referee.name}`);

  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...COLORS.dark);
  doc.text(`Referee: ${referee.name}`, 14, 36);
  if (referee.phone) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.gray);
    doc.text(`Phone: ${referee.phone}`, 14, 42);
  }

  const tableData = matches
    .filter((m) => m.referee_id === referee.id)
    .sort((a, b) => new Date(a.scheduled_at).getTime() - new Date(b.scheduled_at).getTime())
    .map((m) => [
      format(new Date(m.scheduled_at), "HH:mm"),
      m.pitch?.name ?? "–",
      m.group?.name ?? "–",
      m.home_team?.name ?? "TBD",
      m.away_team?.name ?? "TBD",
      "",
      "",
    ]);

  autoTable(doc, {
    startY: 48,
    head: [["Time", "Pitch", "Group", "Home", "Away", "Home Score", "Away Score"]],
    body: tableData,
    headStyles: { fillColor: COLORS.primary, textColor: COLORS.white, fontStyle: "bold", fontSize: 8 },
    bodyStyles: { fontSize: 9, minCellHeight: 12 },
    alternateRowStyles: { fillColor: COLORS.light },
    margin: { left: 14, right: 14 },
  });

  addFooter(doc, 1, 1);
  doc.save(`${tournament.name.replace(/\s+/g, "-")}-referee-${referee.name.replace(/\s+/g, "-")}.pdf`);
}

export function exportTeamSchedule(
  tournament: Tournament,
  team: Team,
  matches: Match[],
  locale = "en"
): void {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  addHeader(doc, tournament, `Team Schedule — ${team.name}`);

  const teamMatches = matches
    .filter((m) => m.home_team_id === team.id || m.away_team_id === team.id)
    .sort((a, b) => new Date(a.scheduled_at).getTime() - new Date(b.scheduled_at).getTime());

  const tableData = teamMatches.map((m) => {
    const isHome = m.home_team_id === team.id;
    const opponent = isHome ? m.away_team?.name : m.home_team?.name;
    const result =
      m.status === "completed"
        ? isHome
          ? `${m.home_score ?? 0}–${m.away_score ?? 0}`
          : `${m.away_score ?? 0}–${m.home_score ?? 0}`
        : "–";
    return [
      format(new Date(m.scheduled_at), "HH:mm"),
      m.pitch?.name ?? "–",
      m.group?.name ?? "–",
      isHome ? "Home" : "Away",
      opponent ?? "TBD",
      result,
    ];
  });

  autoTable(doc, {
    startY: 34,
    head: [["Time", "Pitch", "Group", "H/A", "Opponent", "Score"]],
    body: tableData,
    headStyles: { fillColor: COLORS.primary, textColor: COLORS.white, fontStyle: "bold", fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    alternateRowStyles: { fillColor: COLORS.light },
    margin: { left: 14, right: 14 },
  });

  addFooter(doc, 1, 1);
  doc.save(`${team.name.replace(/\s+/g, "-")}-schedule.pdf`);
}
